ALTER TABLE models ADD COLUMN IF NOT EXISTS model_type TEXT NOT NULL DEFAULT 'llm';
ALTER TABLE models ADD COLUMN IF NOT EXISTS base_url TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS max_tokens INTEGER;
ALTER TABLE models ADD COLUMN IF NOT EXISTS temperature REAL;
ALTER TABLE models ADD COLUMN IF NOT EXISTS max_retrieved_chunks INTEGER;
ALTER TABLE models ADD COLUMN IF NOT EXISTS max_retrieved_chars INTEGER;
ALTER TABLE models ADD COLUMN IF NOT EXISTS max_embedding_candidates INTEGER;
ALTER TABLE models ADD COLUMN IF NOT EXISTS embedding_batch_size INTEGER;

ALTER TABLE model_access ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT false;
